#!/usr/bin/env bash

export CONTECO_LABEL="filebeat.sasl - ContEco"
export CONTECO_DESCRIPTION="ContEco ElasticSearch Filebeat image, with SASL authentication."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="sasl"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="external.filebeat:7.1.1"
export CONTECO_BUILD="image-base"
