#!/usr/bin/env bash

export CONTECO_LABEL="filebeat.ssl - ContEco"
export CONTECO_DESCRIPTION="Filebeat SSL image, with templated default configuration."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="ssl"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="external.filebeat:7.1.1"
export CONTECO_BUILD="image-base"
