filebeat.inputs:
- type: log
  paths: "${ES_FILEBEAT_FILEPATHS:'/var/log/*.log'}"

output.console:
  enabled: ${ES_FILEBEAT_OUTPUT_CONSOLE:false}
  pretty: false

output.elasticsearch:
  enabled: ${ES_FILEBEAT_OUTPUT_ELASTICSEARCH:false}
  ssl.enabled: true
  hosts: ${ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS:'elasticsearch:9200'}
  username: "${ES_FILEBEAT_OUTPUT_CONFIG_ELISTICSEARCH_USERNAME}"
  password: "${ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_PASSWORD}"
  index: "${ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX:'filebeat'}-%{[beat.version]}-%{+yyyy.MM.dd}"

setup.template.name: "${ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX:'filebeat'}-%{[beat.version]}"
setup.template.pattern: "${ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX:'filebeat'}-%{[beat.version]}-*"

setup.kibana.host: ${ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_HOST:"kibana:5601"}
setup.dashboards.enabled: ${ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS:false}

output.kafka:
  enabled: ${ES_FILEBEAT_OUTPUT_KAFKA:false}
  ssl.enabled: true
  hosts: ${ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_HOSTS:"kafka:9092"}
  username: "${ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_USERNAME}"
  password: "${ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_PASSWORD}"
  topic: '${ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_TOPIC:es_filebeat_kafka}'
  version: "2.0.0"
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

logging.level: warning
logging.metrics.enabled: false
logging.metrics.period: 30s
logging.json: false
